debugMode: true
sparkHadoopF3S3AConfig:
 spark.hadoop.fs.s3a.endpoint: "{{.minio_endpoint}}"
 spark.hadoop.fs.s3a.access.key: "{{.minio_access_key}}"
 spark.hadoop.fs.s3a.secret.key: "{{.minio_secret_key}}"
 spark.hadoop.fs.s3a.path.style.access: "true"
 spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
 spark.hadoop.fs.AbstractFileSystem.s3a.impl: "org.apache.hadoop.fs.s3a.S3A"
 s3.filename: "s3a://ditas.dummy-example/ditas-blood-tests.parquet"

jdbcConfig:
 db.mysql.url: "jdbc:mysql://{{.mysql_hostname}}/ditas_dummy_example?autoReconnect=true&useSSL=false"
 db.mysql.username: "{{.mysql_username}}"
 db.mysql.password: "{{.mysql_password}}"

policyEnforcementUrl: "http://localhost:{{.policy_enforcement_port}}/rewrite-sql-query"


jwtServerTimeout: 5000 #milliseconds
jwksServerEndpoint:  {{.keycloack_url}}/auth/realms/{{.keycloack_realm}}/protocol/openid-connect/certs # OSR
jwksCheckServerCertificate: false


showDataFrameLength: 10

dataTables:
 blood_tests: "s3a://ditas.dummy-example/documents-10000.parquet"
 consent: "s3a://ditas.dummy-example/consents.Consents10000Demo"
 blood_tests_clauses: "s3a://ditas.dummy-example/blood_tests_10000.clausesDemo"
 blood_tests_rules: "s3a://ditas.dummy-example/blood_tests_10000.rulesDemo"
 patientsProfiles: patient_priv
 patientsProfiles_clauses: patient10000_clausesDemo
 patientsProfiles_rules: patient10000_rulesDemo

dataTablesTypes:
 blood_tests_type: s3a
 consent_type: s3a
 blood_tests_clauses_type: s3a
 blood_tests_rules_type: s3a
 patientsProfiles_type: jdbc
 patientsProfiles_clauses_type: jdbc
 patientsProfiles_rules_type: jdbc


port: {{.data_movement_dal_port}}
